version: '3'

services:
  pedro-postgresql:
    image: postgres:12.9-bullseye
    container_name: pedro-postgresql
    hostname: pedro-postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  app:
    build: "."
    container_name: 'pedro-back'
    ports:
      - "0.0.0.0:80:80"
    environment:
      - SECRET_KEY
      - DATABASE_HOST
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_PORT
    depends_on:
      - 'pedro-postgresql'

