# Generated by Django 5.0.4 on 2024-04-20 10:10

import applications.members.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_position_workposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='group',
        ),
        migrations.AlterField(
            model_name='user',
            name='time_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=applications.members.models.upload_avatar),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.workposition'),
        ),
        migrations.DeleteModel(
            name='TagGroup',
        ),
        migrations.DeleteModel(
            name='TimePreference',
        ),
    ]
