# Generated by Django 5.0.4 on 2024-04-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_last_message'),
        ('matches', '0002_meeting_meetingmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='state',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='meetingmember',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='matches.meeting'),
        ),
    ]
